### PR TITLE
Improve performance, update readme

### PR DESCRIPTION
**Pull request by FistMeNaruto**
Hi!

I have updated `package.json` `main` property to point to `dist/index.js` so it would be possible to use `import 'confetti-js'` inside of components.

I have also replaced `setInterval(draw, 20)` with `requestAnimationFrame()` which improves performance significantly. This basically syncs the `draw` function with repaints. It is well supported by most browsers and you can expand that number by adding prefix fallbacks, but I don't think that's necessary. [caniuse requestAnimationFrame](https://caniuse.com/#feat=requestanimationframe)

Feel free to discuss changes :)

### CODE REVIEW

**Comment by Agezao** [comment]
Hey, that's pretty good! Thanks for the work you've put in making the lib better.
By tonight I'll me merging the pull request and updating npm with the new release.

Congrats and thanks!! :))

**Comment by FistMeNaruto** [comment]
Hey, no problem, thanks for the lib! :)

**Comment by FistMeNaruto** [comment]
Hi!

Are you going to release the update to npm? I'm planning on releasing a new project and it deserves some confetti :) It's not a big issue for me to use the forked version, but it would be nice to pull confetti straight from npm

**Comment by Agezao** [comment]
Hey! Sorry for the late. I'm a mess.

Nonetheless, PR approved and npm updated!
Thanks again for the PR, you are _the real MVP_.

**Pull request merged**
