### PR TITLE
Toggle to prevent confettis from respawning endlessly

### LINKED ISSUE #9: Feature request: Begin falling from top and stop until confetti is over
Hi, thanks for the wonderful and so small library. To make a better visual effect I'm looking for ways to start the animation so the confetti falls from top to bottom instead of start with the whole screen filled. And also a new method, eg stop(), that would stop new confetti so that current confetti keeps falling until no more confetti is on screen.

If that is not clear I can try explaining it better and if you don't think that is useful I can understand and so the issue can be closed ;-)

### PR DESCRIPTION
**Pull request by qortex**
Fixes #9 .

Putting `respawn` setting to false prevents confettis from being respawned when they go off-screen. Allows for confettis to be gently going offscreen instead of disappearing all at the same time.

### CODE REVIEW

**Comment by Agezao** [comment]
Hi Michael,

Awesome work. Thanks for the effort in improving the lib;

I've already revised the PR code but I'm currently out-of-office to merge and test it, later today or tomorrow I'll tackle these tasks and give you a follow-up; 😄

**Comment by qortex** [comment]
sorry about the auto-delete of trailing whitespace!

**Comment by qortex** [comment]
Don't know if I needed to commit dist files too, I build them using `yarn build`.

**Comment by Agezao** [comment]
It's okey, the trailing spaces have no impact on the final result anyway. Back in the days when I built this code, I wasn't using any IDE with _eslint_ or similar so these kinds of _code-formatting_ patterns did not get applied;

About the build, it's a good practice but not necessary since before pushing to NPM I rebuild the lib. Actually, the built files should not be on master at all haha. I'm starting to consider a refactoring for this lib where I address a better code architecture and overall CI/CD behaviors like this;

**Comment by qortex** [comment]
Let me know if there's anything I can help with to move this forward :)

**Comment by Agezao** [comment]
Hi @MicMicMon!

PR merged and published on NPM 🎉  _(https://github.com/Agezao/confetti-js/releases/tag/0.0.17)_

Thanks for the work, and sorry for the delay 😅!

**Pull request merged**
